# Generated by Django 5.0.4 on 2024-04-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Population",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("year", models.PositiveSmallIntegerField()),
                ("human_count", models.PositiveBigIntegerField()),
            ],
        ),
    ]
